kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  volumes:
  - name: cache
    path: /tmp/cache
  commands:
  - pwd
  - ls /tmp/cache
  - echo hello
  - echo world

volumes:
- name: lib
  host:
    path: /var/lib
