kind: pipeline
type: docker
name: default

steps:
- name: greeting
  image: alpine
  volumes:
  - name: lib
    path: /tmp/cache
  commands:
  - docker pull node
  - docker save node:latest -o /tmp/cache.node.tar
  - pwd
  - ls /tmp/cache
  - echo hello
  - echo world

volumes:
- name: lib
  host:
    path: /var/lib
